---
- name: Copy pdns.cnf
  template:
    src: pdns.conf.j2
    dest: "{{ pdns_admin_conf_filepath }}"
    owner: root
    group: root

- name: Make PowerDNS as service
  template:
    src: powerdns-admin.service.j2
    dest: "{{ pdns_admin_systemd_filepath }}"
    owner: root
    group: root
