---
- name: Copy {{ pdns_admin_conf_filename }}
  template:
    src: "{{ pdns_admin_conf_template_filename }}"
    dest: "{{ pdns_admin_conf_filepath }}"
    owner: root
    group: root
  notify: Restart Powerdns Admin Service

  tags:
    - generate-config

- name: Drop PowerDNS Admin systemd file
  template:
    src: "{{ pdns_admin_systemd_template_filename }}"
    dest: "{{ pdns_admin_systemd_filepath }}"
    owner: root
    group: root
  register: _systemd

- name: Make PowerDNS Admin as service
  systemd:
    name: "{{ pdns_admin_systemd_filename }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: _systemd.changed

- name: Run Create DB
  shell: "{{ pdns_admin_python_path }} /var/www/powerdns-admin/create_db.py"
  when:
    - inventory_hostname in groups['pdns-int-master', 'pdns-pub-master', 'pdns-master']
