---
- name: apt update
  apt:
    update_cache: yes

- name: Install list of packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items: "{{ pdns_admin_packages }}"

- name: Get pip
  shell: curl https://bootstrap.pypa.io/get-pip.py | python

- name: Creates directory
  file:
    path: /var/www
    state: directory

- name: Git clone power admin
  git:
    repo: "{{ pdns_admin_git_repo_url }}"
    dest: "{{ pdns_admin_path }}"

- name: Install virtualenv
  pip:
    name: virtualenv

- name: Create virtualenv
  command: "virtualenv {{ pdns_admin_python_venv_path }}"
  ignore_errors: yes

- name: pip install
  pip:
    requirements: "{{ pdns_admin_path }}/requirements.txt"
    virtualenv: "{{ pdns_admin_python_venv_path }}"

- name: pip install mysql-python
  pip:
    name: mysql-python
    virtualenv: "{{ pdns_admin_python_venv_path }}"

# TODO: Run at the frist time only
# - name: Initial DB for PowerDNS Admin
#   command: python /var/www/powerdns-admin/create_db.py
