---
- name: Copy {{ pdns_admin_conf_filename }}
  template:
    src: "{{ pdns_admin_conf_template_filename }}"
    dest: "{{ pdns_admin_conf_filepath }}"
    owner: root
    group: root

- name: Make PowerDNS Admin as service
  template:
    src: "{{ pdns_admin_systemd_template_filename }}"
    dest: "{{ pdns_admin_systemd_filepath }}"
    owner: root
    group: root

- name: Run Create DB
  shell: /var/www/powerdns-admin/create_db.py

- name: Run Powerdns Admin
  shell: /var/www/powerdns-admin/run.py