---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items: "{{ pdns_admin_packages }}"

- name: Install Python PIP
  shell: pip --version || curl https://bootstrap.pypa.io/get-pip.py | python

- name: Create "{{ pdns_admin_root_path }}" directory
  file:
    path: "{{ pdns_admin_root_path }}"
    state: directory

- name: Git clone PowerDNS Admin
  git:
    repo: "{{ pdns_admin_git_repo_url }}"
    dest: "{{ pdns_admin_path }}"

- name: Install virtualenv
  pip:
    name: virtualenv

- name: PIP install requirements for PowerDNS Admin
  pip:
    requirements: "{{ pdns_admin_requirements_path }}"
    virtualenv: "{{ pdns_admin_python_venv_path }}"

- name: Install some more required packages
  pip:
    name: "{{ item }}"
    virtualenv: "{{ pdns_admin_python_venv_path }}"
  with_items: "{{ pdns_admin_pip_packages }}"
