---
- name: Add Telegraf apt-key
  apt_key:
    url: "https://repos.influxdata.com/influxdb.key"
    state: present

- name: Add Telegraf repository
  apt_repository:
    repo: "deb https://repos.influxdata.com/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Telegraf
  apt:
     pkg: "{{ telegraf_service_name }}"
     state: latest
     update_cache: yes
