---
- name: apt update
  apt:
    update_cache: yes

- name: Install list of packages
  apt: 
    name: "{{ item }}"
    state: installed
  with_items:
    - curl
    - git
    - python
    - libpython2.7
    - python-dev
    - libsasl2-dev
    - build-essential
    - libmariadb2
    - libmariadb-client-lgpl-dev
    - libssl-dev
    - libldap2-dev
    - libmysqlclient-dev

- name: Get pip
  shell: curl https://bootstrap.pypa.io/get-pip.py | python

- name: Creates directory
  file: 
    path: /var/www
    state: directory

- name: Git clone power admin
  git:
    repo: https://github.com/ngoduykhanh/PowerDNS-Admin.git
    dest: /var/www/powerdns-admin

- name: Install virtualenv
  pip:
    name: virtualenv

- name: Create virtualenv
  command: virtualenv /opt/vens/powerdns

- name: pip install
  pip: 
    requirements: /var/www/powerdns-admin/requirements.txt
    virtualenv: /opt/vens/powerdns

- name: pip install mysql-python
  pip:
    name: mysql-python

- name: copy config.py
  command: cp /var/www/powerdns-admin/config_template.py /var/www/powerdns-admin/config.py

# TODO: Run at the frist time only
# - name: Initial DB for PowerDNS Admin
#   command: python /var/www/powerdns-admin/create_db.py




