---
- block: # Prepare Ceph repository
  - name: Add Ceph repository key
    apt_key:
      url: "{{ cephfs_apt_key_url }}"
      state: present

  - name: Add Ceph repository
    apt_repository:
      repo: "{{ cephfs_deb_repository }}"
      state: present
