---
- name: Mount CephFS
  mount:
    name: "{{ item.name }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts | default(omit) }}"
    state: mounted
  with_items: "{{ cephfs_mounts }}"
  when: cephfs_mounts is defined
